In [1]:
%load_ext autoreload
%autoreload 2

import hwacctools.quantization.quant as q
from stim_lib.stimulus_gen import generate_qracc_inputs
import numpy as np
import plotly.express as px
import seaborn as sns
import pandas as pd
import plotly.subplots as sp

df = pd.DataFrame
sns.set_theme()

In [2]:
w,x,wxb = generate_qracc_inputs(
    wDimX = 32, #nColumns
    wDimY = 128, #nRows
    xBatches = 10,
    xTrits = 7,
    outBits = 4,
    seed = 0,
    weight_mode = 'bipolar',
    col_symmetric=False,
    clip_output = False
)

[STIM_GEN] Generating random weights


In [3]:
df(wxb)

0    1     2     3     4     5     6    7     8    9   ...    22    23  \
0  -995  779  -475  -995   321  -443   531 -215   963 -425  ...  -981   751   
1   588  472  2166   374   -56  -404 -1208 -144   780 -664  ...  -566  -536   
2 -1373  521   991 -1109  -339  1141  -555 -167    73  -71  ...  -525   813   
3 -1354 -410  1474   826  1228  -750   700 -614  -724  592  ...  -372  -278   
4   887  627  -235   267   197  -911   -37  137  -367  -31  ...   519  -177   
5   894 -628   100   306 -1690  -312  -356 -878  -486 -590  ... -1322  -592   
6   526  140  -906   210   806  2582  -828  842 -1862 -212  ...  -954  -986   
7  -703  111 -1237 -1037   227   961 -1181 -845   117 -529  ...  -947   -59   
8   377  495   309  1937  -439   305  -727 -429   -37  651  ...    25  1101   
9  -128   74   706   824  1054  -248  -766  200  -552 -606  ...  -392  -654   

     24    25    26    27    28    29    30    31  
0  -607  -707  1895  -425    99    57   765  -611  
1 -1298   474   756  1072  -766  1610  -218  1294  
2   399  -423   581 -1035  1005  -905  -701   299  
3  -474   292 -1200   220  -266  -880  -708   208  
4  -155   773  -221   339  -527   323  -783  1377  
5   702  -342  -414   232    18  -194  -272   542  
6   -50    28  -678  -432  -414  1186 -1672   744  
7  -691  -543   223 -1637  1217  1103   577   805  
8    -5 -1999  -419 -1927  -963   -99  1707  1021  
9  -336  -244  -836    38   220   378  -244  -314  

[10 rows x 32 columns]

In [4]:
df(rtl)

NameError: name 'rtl' is not defined

In [6]:
rtl = np.loadtxt('../tb/seq_acc/inputs/mac_out_rtl_bipolar.txt')
px.scatter(x=rtl.flatten(), y=wxb.T[::-1].T.flatten(), title='RTL vs Python MAC output', labels={'x':'RTL', 'y':'Python'},
    width=400,height=400
)

In [11]:
x[0]

array([-123,  124,  -48,    0, -106,   -6,  -12,  -25, -117, -111, -125,
        -81,   62,   47,  -17,  -95,  104,   24,   62,    2,  -91,  -38,
       -119,  -80,  -36, -127,   36, -101,   63,  -16,   53,  107,   23,
         32,    2,  -34, -124, -124,  -29,  -11,   37,   43,  -17, -107,
        106,    6,   89,  -44,   55,  102, -124,  -44,   24,  -79,  -33,
         31,   90,    8,   43,   13, -123,  113,   28,   77,  -16,   75,
        125,   44,   54,  111,   11,  116,  -84, -121,   72, -127,  -76,
         35,  -31, -104,   65,   72,   31, -109,  -95, -125,   39, -115,
        -63,   -1,  125,  -55, -124,   14,   -1,   91,    4,  103,   71,
          7,   21,  -69, -125,   86,   48,   53,  -69,  -17,  -45,  127,
        -47,  -70,   44,  -94,  107,  -58,   94,  -48,  -38,  110,  118,
       -103,  -27,   61,   -6,  -63,   62,  -50])

: 

: 

: 

: 

In [ ]:
q.simulate_trit_mul(w, x[0], 7, verbose=True)

x trits:
     0  1  2  3  4  5  6
0   -1 -1 -1 -1  0 -1 -1
1    1  1  1  1  1  0  0
2    0 -1 -1  0  0  0  0
3    0  0  0  0  0  0  0
4   -1 -1  0 -1  0 -1  0
..  .. .. .. .. .. .. ..
123  0  1  1  1  1  0  1
124  0  0  0  0 -1 -1  0
125  0 -1 -1 -1 -1 -1 -1
126  0  1  1  1  1  1  0
127  0 -1 -1  0  0 -1  0

[128 rows x 7 columns]
partials:
   0   1   2   3   4   5   6   7   8   9   ...  22  23  24  25  26  27  28  \
0  -4  12   2   4  -8  16 -10  -4   6  -6  ...  -6   8  -8   6  -8   2 -14   
1  -3  -1  -3  -1   5  19  -3  -5   3  -9  ...  -3   7   9   3   3  -1  -3   
2  -5  -1   1  -5   1   5   7  -9  11  -9  ...   9  13  -1  -1  -3   9   1   
3 -17   1   3  -5  -5   9  -1  -5   7 -13  ...  -9   1   5   3   1   7   1   
4  -8   8  -4  -4  -6  14  -8   2   4  -8  ...  -6   2  -6   6  -2   2  -2   
5   1  -1   1   3 -13  19 -19  -7   7 -13  ...   1  -1   1   9   9   7  -3   
6 -13   7  -1   5   1  17  -5  -1   9  -3  ...   5   5   7   1   3   3 -13   

   29  30  31  
0  -6  10  -2  


array([-9.950e+02,  7.790e+02, -4.750e+02, -9.950e+02,  3.210e+02,
       -4.430e+02,  5.310e+02, -2.150e+02,  9.630e+02, -4.250e+02,
        1.387e+03, -6.300e+01,  1.750e+02,  5.410e+02, -3.270e+02,
        1.223e+03, -3.550e+02, -1.000e+00,  6.370e+02,  2.093e+03,
        1.595e+03,  1.750e+02, -9.810e+02,  7.510e+02, -6.070e+02,
       -7.070e+02,  1.895e+03, -4.250e+02,  9.900e+01,  5.700e+01,
        7.650e+02, -6.110e+02])

: 

: 

: 

: 

In [ ]:
x @ w.T

array([[ -995,   779,  -475,  -995,   321,  -443,   531,  -215,   963,
         -425,  1387,   -63,   175,   541,  -327,  1223,  -355,    -1,
          637,  2093,  1595,   175,  -981,   751,  -607,  -707,  1895,
         -425,    99,    57,   765,  -611],
       [  588,   472,  2166,   374,   -56,  -404, -1208,  -144,   780,
         -664,   -94,  -942,  -768,   192, -1240,   272,  1236,  1922,
          584,  -554,   508,  -586,  -566,  -536, -1298,   474,   756,
         1072,  -766,  1610,  -218,  1294],
       [-1373,   521,   991, -1109,  -339,  1141,  -555,  -167,    73,
          -71, -1267,  -411,  1013,  -249, -1385,   391,  -319,   703,
           17,   139,    25,   885,  -525,   813,   399,  -423,   581,
        -1035,  1005,  -905,  -701,   299],
       [-1354,  -410,  1474,   826,  1228,  -750,   700,  -614,  -724,
          592,   648,   214,   478,  -518,   754,  1028,  1640,   846,
          -38,    90,   276,  -160,  -372,  -278,  -474,   292, -1200,
          220,  

: 

: 

: 

: 